export const FETCH_ARTIST_REQUEST = 'FETCH_ARTIST_REQUEST';
export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS';
export const FETCH_ARTIST_FAILED = 'FETCH_ARTIST_FAILED';

export const STORE_ARTISTS_PROFILE = 'STORE_ARTISTS_PROFILE';
export const STORE_ARTISTS_TOP_TRACKS = 'STORE_ARTISTS_TOP_TRACKS';
export const STORE_ARTISTS_RELATED_ARTISTS = 'STORE_ARTISTS_RELATED_ARTISTS';
export const STORE_ARTISTS_ALBUMS = 'STORE_ARTISTS_ALBUMS';