export const FETCH_ARTIST_REQUEST = 'FETCH_ARTIST_REQUEST';
export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS';
export const FETCH_ARTIST_FAILED = 'FETCH_ARTIST_FAILED';
export const FETCH_ARTIST_ABORT = 'FETCH_ARTIST_ABORT';

export const STORE_ARTIST_TOP_TRACK_IDS = 'STORE_ARTIST_TOP_TRACK_IDS';
export const STORE_ARTIST_ALBUM_IDS = 'STORE_ARTIST_ALBUM_IDS';
export const STORE_ARTIST_RELATED_ARTIST_IDS = 'STORE_ARTIST_RELATED_ARTIST_IDS';
