export const FETCH_CATEGORIES_PLAYLISTS_REQUEST = 'FETCH_CATEGORIES_PLAYLISTS_REQUEST';
export const FETCH_CATEGORIES_PLAYLISTS_SUCCESS = 'FETCH_CATEGORIES_PLAYLISTS_SUCCESS';
export const FETCH_CATEGORIES_PLAYLISTS_FAILED = 'FETCH_CATEGORIES_PLAYLISTS_FAILED';
export const FETCH_CATEGORIES_PLAYLISTS_ABORT = 'FETCH_CATEGORIES_PLAYLISTS_ABORT';

export const STORE_CATEGORIES_PLAYLISTS = 'STORE_CATEGORIES_PLAYLISTS';