export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_FAILED = 'FETCH_CATEGORY_FAILED';
export const FETCH_CATEGORY_ABORT = 'FETCH_CATEGORY_ABORT';

export const STORE_CATEGORY_PLAYLIST_IDS = 'STORE_CATEGORY_PLAYLIST_IDS';