export const STORE_ARTISTS = 'STORE_ARTISTS';
export const STORE_ALBUMS = 'STORE_ALBUMS';
export const STORE_PLAYLISTS = 'STORE_PLAYLISTS';
export const STORE_CATEGORIES = 'STORE_CATEGORIES';
export const STORE_TRACKS = 'STORE_TRACKS';