export const FOLLOW_ARTIST_REQUEST = 'FOLLOW_ARTIST_REQUEST';
export const FOLLOW_ARTIST_SUCCESS = 'FOLLOW_ARTIST_SUCCESS';
export const FOLLOW_ARTIST_FAILED = 'FOLLOW_ARTIST_FAILED';

export const UNFOLLOW_ARTIST_REQUEST = 'UNFOLLOW_ARTIST_REQUEST';
export const UNFOLLOW_ARTIST_SUCCESS = 'UNFOLLOW_ARTIST_SUCCESS';
export const UNFOLLOW_ARTIST_FAILED = 'UNFOLLOW_ARTIST_FAILED';

export const FOLLOW_PLAYLIST_REQUEST = 'FOLLOW_PLAYLIST_REQUEST';
export const FOLLOW_PLAYLIST_SUCCESS = 'FOLLOW_PLAYLIST_SUCCESS';
export const FOLLOW_PLAYLIST_FAILED = 'FOLLOW_PLAYLIST_FAILED';

export const UNFOLLOW_PLAYLIST_REQUEST = 'UNFOLLOW_PLAYLIST_REQUEST';
export const UNFOLLOW_PLAYLIST_SUCCESS = 'UNFOLLOW_PLAYLIST_SUCCESS';
export const UNFOLLOW_PLAYLIST_FAILED = 'UNFOLLOW_PLAYLIST_FAILED';
