export const FETCH_HIGHLIGHTS_REQUEST = 'FETCH_HIGHLIGHTS_REQEUST';
export const FETCH_HIGHLIGHTS_SUCCESS = 'FETCH_HIGHLIGHTS_SUCCESS';
export const FETCH_HIGHLIGHTS_FAILED = 'FETCH_HIGHLIGHTS_FAILED';
export const FETCH_HIGHLIGHTS_ABORT = 'FETCH_HIGHLIGHTS_ABORT';

export const STORE_HIGHLIGHTS = 'STORE_HIGHLIGHTS';