// Standard player related actions

export const STANDARD_SELECT_TRACK = 'STANDARD_SELECT_TRACK';
export const STANDARD_RESUME_PLAYER = 'STANDARD_RESUME_PLAYER';
export const STANDARD_PAUSE_PLAYER = 'STANDARD_PAUSE_PLAYER';
export const STANDARD_SKIP_FORWARDS = 'STANDARD_SKIP_FORWARDS';
export const STANDARD_SKIP_BACKWARDS = 'STANDARD_SKIP_BACKWARDS';
export const STANDARD_SET_SHUFFLE = 'STANDARD_SET_SHUFFLE';
export const STANDARD_SET_REPEAT = 'STANDARD_SET_REPEAT';



// SDK player related actions
export const CONFIRM_SDK_AVAILABLE = 'CONFIRM_SDK_AVAILABLE';

export const SDK_UPDATE_PLAYER_STATE = 'SDK_UPDATE_PLAYER_STATE';

// The rest of these SDK actions currently aren't being used within the reducer, since all of the player
// updates for the SDK player are driven by the SDK_UPDATE_PLAYER_STATE action. The below actions can still
// be useful for debugging however.

export const SDK_SET_SHUFFLE_SUCCESS = 'SDK_SET_SHUFFLE_SUCCESS';
export const SDK_SET_SHUFFLE_FAILED = 'SDK_SET_SHUFFLE_FAILED';

export const SDK_SET_REPEAT_SUCCESS = 'SDK_SET_REPEAT_SUCCESS';
export const SDK_SET_REPEAT_FAILED = 'SDK_SET_REPEAT_FAILED';

export const SDK_SELECT_TRACK_SUCCESS = 'SDK_SELECT_TRACK_SUCCESS';
export const SDK_SELECT_TRACK_FAILED = 'SDK_SELECT_TRACK_FAILED';

export const SDK_RESUME_PLAYER_SUCCESS = 'SDK_RESUME_PLAYER_SUCCESS';
export const SDK_RESUME_PLAYER_FAILED = 'SDK_RESUME_PLAYER_FAILED';

export const SDK_PAUSE_PLAYER_SUCCESS = 'SDK_PAUSE_PLAYER_SUCCESS';
export const SDK_PAUSE_PLAYER_FAILED = 'SDK_PAUSE_PLAYER_FAILED';

export const SDK_SKIP_FORWARDS_SUCCESS = 'SDK_SKIP_FORWARDS_SUCCESS';
export const SDK_SKIP_FORWARDS_FAILED = 'SDK_SKIP_FORWARDS_FAILED';

export const SDK_SKIP_BACKWARDS_SUCCESS = 'SDK_SKIP_BACKWARDS_SUCCESS';
export const SDK_SKIP_BACKWARDS_FAILED = 'SDK_SKIP_BACKWARDS_FAILED';
