export const FETCH_PLAYLIST_REQUEST = 'FETCH_PLAYLIST_REQUEST';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_FAILED = 'FETCH_PLAYLIST_FAILED';
export const FETCH_PLAYLIST_ABORT = 'FETCH_PLAYLIST_ABORT';

export const STORE_PLAYLIST = 'STORE_PLAYLIST';
export const STORE_PLAYLIST_FOLLOW_STATUS = 'STORE_PLAYLIST_FOLLOW_STATUS';

export const UPDATE_PLAYLIST_NAME_REQUEST = 'UPDATE_PLAYLIST_NAME_REQUEST';
export const UPDATE_PLAYLIST_NAME_SUCCESS = 'UPDATE_PLAYLIST_NAME_SUCCESS';
export const UPDATE_PLAYLIST_NAME_FAILED = 'UPDATE_PLAYLIST_NAME_FAILED';

export const UPDATE_PLAYLIST_IMAGE_REQUEST = 'UPDATE_PLAYLIST_IMAGE_REQUEST';
export const UPDATE_PLAYLIST_IMAGE_SUCCESS = 'UPDATE_PLAYLIST_IMAGE_SUCCESS';
export const UPDATE_PLAYLIST_IMAGE_FAILED = 'UPDATE_PLAYLIST_IMAGE_FAILED';

export const ADD_TRACK_TO_PLAYLIST_REQUEST = 'ADD_TRACK_TO_PLAYLIST_REQUEST';
export const ADD_TRACK_TO_PLAYLIST_SUCCESS = 'ADD_TRACK_TO_PLAYLIST_SUCCESS';
export const ADD_TRACK_TO_PLAYLIST_FAILED = 'ADD_TRACK_TO_PLAYLIST_FAILED';

export const REMOVE_TRACK_FROM_PLAYLIST_REQUEST = 'REMOVE_TRACK_FROM_PLAYLIST_REQUEST';
export const REMOVE_TRACK_FROM_PLAYLIST_SUCCESS = 'REMOVE_TRACK_FROM_PLAYLIST_SUCCESS';
export const REMOVE_TRACK_FROM_PLAYLIST_FAILED = 'REMOVE_TRACK_FROM_PLAYLIST_FAILED';
