export const FETCH_PLAYLIST_REQUEST = 'FETCH_PLAYLIST_REQUEST';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_FAILED = 'FETCH_PLAYLIST_FAILED';
export const FETCH_PLAYLIST_ABORT = 'FETCH_PLAYLIST_ABORT';

export const UPDATE_PLAYLIST_NAME_SUCCESS = 'UPDATE_PLAYLIST_NAME_SUCCESS';
export const UPDATE_PLAYLIST_NAME_FAILED = 'UPDATE_PLAYLIST_NAME_FAILED';

export const UPDATE_PLAYLIST_IMAGE_SUCCESS = 'UPDATE_PLAYLIST_IMAGE_SUCCESS';
export const UPDATE_PLAYLIST_IMAGE_FAILED = 'UPDATE_PLAYLIST_IMAGE_FAILED';

export const ADD_TRACK_TO_PLAYLIST_SUCCESS = 'ADD_TRACK_TO_PLAYLIST_SUCCESS';
export const ADD_TRACK_TO_PLAYLIST_FAILED = 'ADD_TRACK_TO_PLAYLIST_FAILED';

export const REMOVE_TRACK_FROM_PLAYLIST_SUCCESS = 'REMOVE_TRACK_FROM_PLAYLIST_SUCCESS';
export const REMOVE_TRACK_FROM_PLAYLIST_FAILED = 'REMOVE_TRACK_FROM_PLAYLIST_FAILED';

export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_FAILED = 'CREAT_PLAYLIST_FAILED';

export const STORE_USER_FOLLOWING_PLAYLIST = 'STORE_USER_FOLLOWING_PLAYLIST';
export const STORE_PLAYLIST_TRACK_IDS = 'STORE_PLAYLIST_TRACK_IDS';