export const FETCH_PLAYLIST_REQUEST = 'FETCH_PLAYLIST_REQUEST';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_FAILED = 'FETCH_PLAYLIST_FAILED';

export const STORE_PLAYLIST = 'STORE_PLAYLIST';