export const SELECT_TRACK_REQUEST = 'SELECT_TRACK_REQUEST';
export const SELECT_TRACK_SUCCESS = 'SELECT_TRACK_SUCCESS';
export const SELECT_TRACK_FAILED = 'SELECT_TRACK_FAILED';


export const PLAY_CURRENT_TRACK = 'PLAY_CURRENT_TRACK';
export const PAUSE_CURRENT_TRACK = 'PAUSE_CURRENT_TRACK';
export const SKIP_TO_NEXT_TRACK = 'SKIP_TO_NEXT_TRACK';
export const SKIP_TO_PREVIOUS_TRACK = 'SKIP_TO_PREVIOUS_TRACK';
export const SEEK_POSITION_IN_TRACK = 'SEEK_POSITION_IN_TRACK';

export const SET_SHUFFLE_REQUEST = 'SET_SHUFFLE_REQUEST';
export const SET_SHUFFLE_SUCCESS = 'SET_SHUFFLE_SUCCESS';
export const SET_SHUFFLE_FAILED = 'SET_SHUFFLE_FAILED';

export const SET_REPEAT_REQUEST = 'SET_REPEAT_REQUEST';
export const SET_REPEAT_SUCCESS = 'SET_REPEAT_SUCCESS';
export const SET_REPEAT_FAILED = 'SET_REPEAT_FAILED';

export const CONFIRM_SDK_AVAILABLE = 'CONFIRM_SDK_AVAILABLE';

export const UPDATE_PLAYER_STATE = 'UPDATE_PLAYER_STATE';


export const SDK_SELECT_TRACK_SUCCESS = 'SDK_SELECT_TRACK_SUCCESS';
export const SDK_SELECT_TRACK_FAILED = 'SDK_SELECT_TRACK_FAILED';