export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const FETCH_USER_ABORT = 'FETCH_USER_ABORT';

export const STORE_USERS_PROFILE = 'STORE_USERS_PROFILE';
