export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const STORE_USERS_PROFILE = 'STORE_USERS_PROFILE';
export const STORE_USERS_TOP_ARTISTS = 'STORE_USERS_TOP_ARTISTS';
export const STORE_USERS_RECENT_TRACKS = 'STORE_USERS_RECENT_TRACKS';
export const STORE_USERS_PLAYLISTS = 'STORE_USERS_PLAYLISTS';

export const SET_MARKET = 'SET_MARKET';